### ISSUE TITLE
Error in jaeger-demo-b

### ISSUE THREAD

**Issue by blenolopes** [candyleer/jaeger-java-hello-world#1]
Hi,
I'm running the test of this repository and I'm finding the below error in jaeger-demo-b (cd jaeger-demo-b && mvn spring-boot:run).

NOTE: jaeger-demo-a does not display an error.

`
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /opt/jaeger-demoa-demob/jaeger-java-hello-world/jaeger-demo-b/src/main/java/io/github/candyleer/jaegerdemob/WebConfig.java:[13,8] io.github.candyleer.jaegerdemob.WebConfig is not abstract and does not override abstract method getMessageCodesResolver() in org.springframework.web.servlet.config.annotation.WebMvcConfigurer
[INFO] 1 error
`

**Comment by blenolopes** [comment]
Running mvn with -X (debug), I have this detailing.
Does anyone have a solution?

Thanks for listening.

`
[ERROR] /opt/jaeger-demoa-demob/jaeger-java-hello-world/jaeger-demo-b/src/main/java/io/github/candyleer/jaegerdemob/WebConfig.java:[13,8] io.github.candyleer.jaegerdemob.WebConfig is not abstract and does not override abstract method getMessageCodesResolver() in org.springframework.web.servlet.config.annotation.WebMvcConfigurer
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jaeger-demo-b: Compilation failure
/opt/jaeger-demoa-demob/jaeger-java-hello-world/jaeger-demo-b/src/main/java/io/github/candyleer/jaegerdemob/WebConfig.java:[13,8] io.github.candyleer.jaegerdemob.WebConfig is not abstract and does not override abstract method getMessageCodesResolver() in org.springframework.web.servlet.config.annotation.WebMvcConfigurer

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/opt/jaeger-demoa-demob/jaeger-java-hello-world/jaeger-demo-b/src/main/java/io/github/candyleer/jaegerdemob/WebConfig.java:[13,8] io.github.candyleer.jaegerdemob.WebConfig is not abstract and does not override abstract method getMessageCodesResolver() in org.springframework.web.servlet.config.annotation.WebMvcConfigurer

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 23 more
[ERROR]
`

**Comment by blenolopes** [comment]
Resolved, implemented "abstract" in WebConfig.java.
